
export default {
    FETCH_CATEGORIES : 'FETCH_CATEGORIES',
    FETCH_CATEGORIES_SUCCESS : 'FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAILURE : 'FETCH_CATEGORIES_FAILURE',
    CHANGE_SELECTED_CATEGORY : 'CHANGE_SELECTED_CATEGORY'
}