const FETCH_CATS = 'FETCH_CATS';
const FETCH_CATS_SUCCESS = 'FETCH_CATS_SUCCESS';
const FETCH_CATS_FAILURE = 'FETCH_CATS_FAILURE';

export default {
    FETCH_CATS,
    FETCH_CATS_SUCCESS,
    FETCH_CATS_FAILURE
}